import { defineLineNet } from '../definition';
import type { LineNetDefinition } from '../types';

export function createChronoInitiationGridDefinition(): Readonly<LineNetDefinition> {
  return defineLineNet(
    {
      nodes: [
        { id: 'glyph-core', position: [0.18, 0.28], label: 'Chrono Core' },
        { id: 'glyph-top', position: [0.18, 0.16], label: 'North Vector' },
        { id: 'glyph-right', position: [0.28, 0.28], label: 'East Vector' },
        { id: 'glyph-bottom', position: [0.18, 0.4], label: 'South Vector' },
        { id: 'glyph-left', position: [0.08, 0.28], label: 'West Vector' },
        { id: 'glyph-link', position: [0.18, 0.48], label: 'Glyph Link' },
        { id: 'spine-entry', position: [0.22, 0.58], label: 'Initiation Gate' },
        { id: 'spine-mid', position: [0.44, 0.62], label: 'Phase Relay' },
        { id: 'spine-cross', position: [0.6, 0.54], label: 'Cross Node' },
        { id: 'spine-terminal', position: [0.82, 0.46], label: 'Terminal Beacon' },
        { id: 'halo-upper', position: [0.66, 0.34], label: 'Halo Upper' },
        { id: 'halo-lower', position: [0.72, 0.7], label: 'Halo Lower' },
        { id: 'spine-orbit', position: [0.52, 0.42], label: 'Orbit Anchor' },
        { id: 'glyph-diagonal', position: [0.12, 0.22], label: 'Glyph Diagonal' },
      ],
      edges: [
        {
          id: 'glyph-top-right',
          from: 'glyph-top',
          to: 'glyph-right',
          weight: 0.9,
          segments: [{ kind: 'line', to: [0.28, 0.28] }],
        },
        {
          id: 'glyph-right-bottom',
          from: 'glyph-right',
          to: 'glyph-bottom',
          weight: 0.9,
          segments: [{ kind: 'line', to: [0.18, 0.4] }],
        },
        {
          id: 'glyph-bottom-left',
          from: 'glyph-bottom',
          to: 'glyph-left',
          weight: 0.9,
          segments: [{ kind: 'line', to: [0.08, 0.28] }],
        },
        {
          id: 'glyph-left-top',
          from: 'glyph-left',
          to: 'glyph-top',
          weight: 0.9,
          segments: [{ kind: 'line', to: [0.18, 0.16] }],
        },
        {
          id: 'glyph-cross-one',
          from: 'glyph-left',
          to: 'glyph-right',
          weight: 0.7,
          segments: [{ kind: 'line', to: [0.28, 0.28] }],
          meta: { group: 'glyph-cross' },
        },
        {
          id: 'glyph-cross-two',
          from: 'glyph-top',
          to: 'glyph-bottom',
          weight: 0.7,
          segments: [{ kind: 'line', to: [0.18, 0.4] }],
          meta: { group: 'glyph-cross' },
        },
        {
          id: 'glyph-link-spine',
          from: 'glyph-bottom',
          to: 'glyph-link',
          weight: 1,
          segments: [{ kind: 'line', to: [0.18, 0.48] }],
        },
        {
          id: 'link-entry',
          from: 'glyph-link',
          to: 'spine-entry',
          weight: 1,
          segments: [
            { kind: 'line', to: [0.22, 0.54] },
            { kind: 'line', to: [0.22, 0.58] },
          ],
        },
        {
          id: 'spine-entry-mid',
          from: 'spine-entry',
          to: 'spine-mid',
          weight: 1.4,
          segments: [
            { kind: 'quadratic', to: [0.36, 0.66], controlPoints: [[0.28, 0.64]] },
            { kind: 'line', to: [0.44, 0.62] },
          ],
        },
        {
          id: 'spine-mid-cross',
          from: 'spine-mid',
          to: 'spine-cross',
          weight: 1.4,
          segments: [
            { kind: 'line', to: [0.52, 0.6] },
            { kind: 'quadratic', to: [0.6, 0.54], controlPoints: [[0.56, 0.58]] },
          ],
        },
        {
          id: 'spine-cross-terminal',
          from: 'spine-cross',
          to: 'spine-terminal',
          weight: 1.4,
          segments: [
            {
              kind: 'cubic',
              to: [0.82, 0.46],
              controlPoints: [
                [0.68, 0.5],
                [0.76, 0.44],
              ],
            },
          ],
        },
        {
          id: 'cross-orbit',
          from: 'spine-cross',
          to: 'spine-orbit',
          weight: 0.8,
          segments: [
            { kind: 'line', to: [0.56, 0.48] },
            { kind: 'line', to: [0.52, 0.42] },
          ],
        },
        {
          id: 'orbit-upper',
          from: 'spine-orbit',
          to: 'halo-upper',
          weight: 0.8,
          segments: [{ kind: 'quadratic', to: [0.66, 0.34], controlPoints: [[0.58, 0.36]] }],
        },
        {
          id: 'cross-lower',
          from: 'spine-cross',
          to: 'halo-lower',
          weight: 0.8,
          segments: [{ kind: 'quadratic', to: [0.72, 0.7], controlPoints: [[0.62, 0.64]] }],
        },
        {
          id: 'glyph-diagonal-link',
          from: 'glyph-diagonal',
          to: 'glyph-core',
          weight: 0.6,
          segments: [{ kind: 'line', to: [0.18, 0.28] }],
        },
        {
          id: 'diagonal-entry',
          from: 'glyph-diagonal',
          to: 'spine-entry',
          weight: 0.6,
          segments: [{ kind: 'quadratic', to: [0.22, 0.58], controlPoints: [[0.16, 0.4]] }],
        },
      ],
      timelines: [
        {
          id: 'intro-core',
          targetType: 'node',
          targetId: 'glyph-core',
          action: 'highlight',
          beat: 0,
          length: 1,
        },
        {
          id: 'ring-top-right',
          targetType: 'edge',
          targetId: 'glyph-top-right',
          action: 'draw',
          beat: 0.4,
          length: 0.6,
        },
        {
          id: 'ring-right-bottom',
          targetType: 'edge',
          targetId: 'glyph-right-bottom',
          action: 'draw',
          beat: 1.1,
          length: 0.6,
        },
        {
          id: 'ring-bottom-left',
          targetType: 'edge',
          targetId: 'glyph-bottom-left',
          action: 'draw',
          beat: 1.8,
          length: 0.6,
        },
        {
          id: 'ring-left-top',
          targetType: 'edge',
          targetId: 'glyph-left-top',
          action: 'draw',
          beat: 2.5,
          length: 0.6,
        },
        {
          id: 'core-pulse',
          targetType: 'node',
          targetId: 'glyph-core',
          action: 'pulse',
          beat: 3.2,
          length: 0.8,
        },
        {
          id: 'cross-diagonal',
          targetType: 'edge',
          targetId: 'glyph-cross-two',
          action: 'draw',
          beat: 3.8,
          length: 0.8,
        },
        {
          id: 'cross-horizontal',
          targetType: 'edge',
          targetId: 'glyph-cross-one',
          action: 'draw',
          beat: 4.2,
          length: 0.8,
        },
        {
          id: 'link-glyph',
          targetType: 'edge',
          targetId: 'glyph-link-spine',
          action: 'draw',
          beat: 4.8,
          length: 0.5,
        },
        {
          id: 'link-entry',
          targetType: 'edge',
          targetId: 'link-entry',
          action: 'draw',
          beat: 5.2,
          length: 0.5,
        },
        {
          id: 'entry-highlight',
          targetType: 'node',
          targetId: 'spine-entry',
          action: 'highlight',
          beat: 5.4,
          length: 0.8,
        },
        {
          id: 'spine-entry',
          targetType: 'edge',
          targetId: 'spine-entry-mid',
          action: 'draw',
          beat: 5.8,
          length: 1.1,
        },
        {
          id: 'mid-highlight',
          targetType: 'node',
          targetId: 'spine-mid',
          action: 'highlight',
          beat: 6.4,
          length: 0.8,
        },
        {
          id: 'mid-cross',
          targetType: 'edge',
          targetId: 'spine-mid-cross',
          action: 'draw',
          beat: 6.8,
          length: 1,
        },
        {
          id: 'cross-highlight',
          targetType: 'node',
          targetId: 'spine-cross',
          action: 'highlight',
          beat: 7.2,
          length: 1.2,
        },
        {
          id: 'cross-terminal',
          targetType: 'edge',
          targetId: 'spine-cross-terminal',
          action: 'draw',
          beat: 7.6,
          length: 1.2,
        },
        {
          id: 'terminal-highlight',
          targetType: 'node',
          targetId: 'spine-terminal',
          action: 'highlight',
          beat: 8.4,
          length: 1,
        },
        {
          id: 'cross-orbit',
          targetType: 'edge',
          targetId: 'cross-orbit',
          action: 'draw',
          beat: 8.8,
          length: 0.6,
        },
        {
          id: 'orbit-highlight',
          targetType: 'node',
          targetId: 'spine-orbit',
          action: 'highlight',
          beat: 9,
          length: 0.8,
        },
        {
          id: 'orbit-upper',
          targetType: 'edge',
          targetId: 'orbit-upper',
          action: 'draw',
          beat: 9.2,
          length: 0.8,
        },
        {
          id: 'upper-highlight',
          targetType: 'node',
          targetId: 'halo-upper',
          action: 'pulse',
          beat: 9.8,
          length: 0.8,
        },
        {
          id: 'cross-lower',
          targetType: 'edge',
          targetId: 'cross-lower',
          action: 'draw',
          beat: 10,
          length: 0.9,
        },
        {
          id: 'lower-highlight',
          targetType: 'node',
          targetId: 'halo-lower',
          action: 'pulse',
          beat: 10.4,
          length: 0.8,
        },
        {
          id: 'diagonal-link',
          targetType: 'edge',
          targetId: 'glyph-diagonal-link',
          action: 'draw',
          beat: 10.8,
          length: 0.6,
        },
        {
          id: 'diagonal-entry',
          targetType: 'edge',
          targetId: 'diagonal-entry',
          action: 'draw',
          beat: 11.2,
          length: 0.8,
        },
      ],
      meta: {
        loopBeats: 12,
        label: 'Chrono Initiation Grid',
      },
    },
    { strict: true },
  );
}

export const chronoInitiationGridDefinition = createChronoInitiationGridDefinition();
